practice1::dump
dot
dump_file
states
def practice1.dump.__dump__(nfa, filename)
Dump the information about NFA.
nfa NFA filename output file
References practice1.dump.__print__.
def practice1.dump.__get_transitions_count(node)
Counts the number of possible transitions.
node node that number of transitions is being searched for count: number of transitions
def practice1.dump.__print__(nfa)
Dump NFA.
Make notes about nodes and their connections nfa nondeterministic finite automaton that need to be print
References practice1.dump.__print_node__, practice1.dump.make_new_state.
Referenced by practice1.dump.__dump__.
def practice1.dump.__print_brief__(node)
Print a summary of the NFA node.
Short output format: 'node.name node.final' node node the debugrmation about which should be output
References practice1.dump.make_new_state.
Referenced by practice1.dump.__print_node__.
def practice1.dump.__print_node__(node)
Printing node of NFA.
Output the name of the node, its final and a list of neighbors with their number node printing node
References practice1.dump.__print_brief__, practice1.dump.make_new_state.
Referenced by practice1.dump.__print__.
def practice1.dump._tree_remove(str top)
Removes all files in the current directory.
top Name of initial directory.
str practice1.dump.make_new_state(node)
Generate new name for id(node) in format: f'q + {id}'.
node node name: new name of node
Referenced by practice1.dump.__print__, practice1.dump.__print_brief__, practice1.dump.__print_node__.